name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile sources
        run: python -m compileall -q .

      - name: Create logs dir
        run: mkdir -p logs

      - name: Smoke dry-run (short)
        run: |
          python scanner.py --config .github/ci.config.yaml --dry-run --reset-progress

